name: test
on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps: 
      - name: "自己紹介"
        run: 
          echo "Nice to meet you!!"
          echo "My Name is Taro!!"
          echo "I love programming!!"
